CREATE TABLE IF NOT EXISTS COUNTRY(
	ID                   BIGINT               NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME                 VARCHAR(100)         NOT NULL,
	LANGUAGE             VARCHAR(100)         NOT NULL,
	TELEPHONE_CODE       VARCHAR(100)         NOT NULL,
	AVERAGE_TEMPERATURE  INTEGER,
	AVERAGE_SNOW_LEVEL   INTEGER,
	HOTTEST_MONTH        VARCHAR(50),
	MOST_SNOWING_MONTH   VARCHAR(50),
	POLAR_NIGHT BOOLEAN,
);

CREATE TABLE IF NOT EXISTS CITY (
	ID BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME              VARCHAR(100) NOT NULL,
	POPULATION        INTEGER NOT NULL,
	CAPITAL BOOLEAN   NOT NULL,
	COUNTRY_ID BIGINT NOT NULL,

	FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PASSPORT (
	ID      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SERIAL  VARCHAR(100) NOT NULL,
	NUMBER  VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS USER_TAB (
	ID          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME        VARCHAR(100) NOT NULL,
	LASTNAME    VARCHAR(100) NOT NULL,
	PASSPORT_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS ORDER_TAB (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRIPTION VARCHAR(100),
	PRICE INTEGER NOT NULL,
	USER_ID BIGINT NOT NULL,
	CITY_ID BIGINT NOT NULL,

	FOREIGN KEY (USER_ID) REFERENCES USER_TAB(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (CITY_ID) REFERENCES CITY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);